library(exifer)

# default metadata work before and after ON1 export -----------------------
# select import folder to act upon
imported <- rstudioapi::selectDirectory(caption = "Select directory",
                            path = paste0("/Volumes/NoBackup/Bilder/Import/", lubridate::year(Sys.Date())))
# tries automagically to determine on which level the prepare_export() should be run
lb <- abs((stringr::str_extract(imported, "\\/(Bilder|Pictures).*") |> 
             stringr::str_count("\\/")) - 4 )

# run the metadata enrichment stuff before exporting photos from ON1
prepare_export(imp_path = imported, level_below = lb)

  # run the cleanup and metadata enrichment stuff after jpg export from ON1
after_export(imp_path = imported,
             exp_path = stringr::str_replace(imported, "Import", "Export/ExportAlbum"))


# metadata transfer -------------------------------------------------------

path_to <- "/Volumes/NoBackup/Bilder/Export/ExportAlbum/2022/34 - Ausflug Jonduri und Papa/"
path_from <- "/Users/Daniel/Pictures/Album/2022/34 - Ausflug Jonduri und Papa/"
modified_since <- "2025-06-20"

transfer_metadata(path_to, path_from, modified_since, delete_original = TRUE)



# run updates manually ------------------------------------------------------
# based on exif-export.csv

paths <- extract_paths() |> 
  dplyr::pull(full)

flatten_subject(paths)
harmonize_lensinfo(paths)
complete_location(paths)
convert35(paths)
harmonize_time(paths)

exiftoolr::exif_call(args = c("-r", "-delete_original!"), path = unique(dirname(paths)))
system(paste0("find '/Volumes/NoBackup/Bilder/Export/ExportAlbum' -name '*xmp' -exec rm {} \\;"))
system(paste0("find '/Users/Daniel/Pictures/Album' -name '*xmp' -exec rm {} \\;"))


# renaming helper ----------------------------------------------------------
# this renames pictures based on a manually created csv file
# (to make file names more congruent, e.g. adding the camera model)
naming <- read_csv("~/Pictures/names.csv") |> 
  select(OLDNAME, NEWNAME)

for (i in 1:nrow(naming)){
  cmd <- paste0("mv '", naming[i, 1], "' '", naming[i, 2], "'")
  
  system(cmd)
}



# update lens info manually -----------------------------------------------
# 
# generate the lensinfo from manually entered variables
# this info is written into a file (lenses.txt) and can then be used
# by using exiftools -@ parameter function
# writes the various tags for the lens name plus the lensinfo
# (which is used for prime/zoom info)
# 
# BE AWARE: It is very important to generate a proper list of affected files first since the info is
# not generated by metadata but hardcoded -> error prone!!!
source("R/helpers.R")

p1 <- "Nikkor Z"
f1 <- "24"
f2 <- "120"
a1 <- "4"
a2 <- ""
p2 <- " S"
m <- "Nikon"

lens <- paste0(p1, " ", f1, ifelse(f2 != "", paste0("-", f2), ""), "mm f/", a1, ifelse(a2 != "", paste0("-", a2), ""), p2)
info <- paste(f1, ifelse(f2 != "", f2, f1), a1, ifelse(a2 != "", a2, a1))

lenses <- c( 
  (paste0("-lens=", lens)), 
  (paste0("-lensmodel=", lens)), 
  (paste0("-lensid=", lens)), 
  (paste0("-lensinfo=", info)),
  paste0("-lensmake=", m))

tibble(lenses) |> 
  write_csv("~/Pictures/Album/lenses.txt",
            col_names = FALSE)

# read PhotoStatistica exif_export.csv for path creation
paths <- extract_paths()
output_paths(paths)

system("exiftool -@ ~/Pictures/Album/lenses.txt -@ ~/Pictures/paths.txt")
