# file contains various manual code which is being used in the context of metadata cleanup

library(exiftoolr)
library(dplyr)
library(readr)
library(lubridate)
library(rstudioapi)
library(stringr)
sapply(list.files("R", pattern = ".*\\.[Rr]", full.names = TRUE), source)


# default metadata work before and after ON1 export -----------------------
# select import folder to act upon
imported <- selectDirectory(caption = "Select directory",
                            path = paste0("/Volumes/NoBackup/Bilder/Import/", year(Sys.Date())))
# tries automagically to determine on which level the prepare_export() should be run
lb <- abs((str_extract(imported, "\\/(Bilder|Pictures).*") |> 
             str_count("\\/")) - 4 )

# run the metadata enrichment stuff before exporting photos from ON1
prepare_export(imp_path = imported, level_below = lb)

# run the cleanup and metadata enrichment stuff after jpg export from ON1
after_export(imp_path = imported)


# metadata transfer -------------------------------------------------------

path_to <- "/Volumes/NoBackup/Bilder/Export/ExportAlbum/2022/34 - Ausflug Jonduri und Papa/"
path_from <- "/Users/Daniel/Pictures/Album/2022/34 - Ausflug Jonduri und Papa/"
modified_since <- "2025-06-20"

transfer_metadata(path_to, path_from, modified_since, delete_original = TRUE)

# renaming helper ----------------------------------------------------------
# this renames pictures based on a manually created csv file
# (to make file names more congruent, e.g. adding the camera model)
naming <- read_csv("~/Pictures/names.csv") |> 
  select(OLDNAME, NEWNAME)

for (i in 1:nrow(naming)){
  cmd <- paste0("mv '", naming[i, 1], "' '", naming[i, 2], "'")
  
  system(cmd)
}


# call location completer manually ----------------------------------------
#  (usually via prepare_import)
complete_location(paths)


# flatten keywords --------------------------------------------------------
#  (usually via prepare_import)
flatten_subject(paths)



# update lens info manually -----------------------------------------------
# 
# generate the lensinfo from manually entered variables
# this info is written into a file (lenses.txt) and can then be used
# by using exiftools -@ parameter function
# writes the various tags for the lens name plus the lensinfo
# (which is used for prime/zoom info)
# 
# BE AWARE: It is very important to generate a proper list of affected files first since the info is
# not generated by metadata but hardcoded -> error prone!!!
source("R/helpers.R")

p1 <- "Apple"
f1 <- "4.25"
f2 <- ""
a1 <- "1.8"
a2 <- ""
p2 <- ""
m <- "Apple"

lens <- paste0(p1, " ", f1, ifelse(f2 != "", paste0("-", f2), ""), "mm f/", a1, ifelse(a2 != "", paste0("-", a2), ""), p2)
info <- paste(f1, ifelse(f2 != "", f2, f1), a1, ifelse(a2 != "", a2, a1))

lenses <- c( 
  (paste0("-lens=", lens)), 
  (paste0("-lensmodel=", lens)), 
  (paste0("-lensid=", lens)), 
  (paste0("-lensinfo=", info)),
  paste0("-lensmake=", m))

tibble(lenses) |> 
  write_csv("~/Pictures/Album/lenses.txt",
            col_names = FALSE)

# read PhotoStatistica exif_export.csv for path creation
paths <- extract_paths()
output_paths(paths)

system("exiftool -@ ~/Pictures/Album/lenses.txt -@ ~/Pictures/paths.txt")


